### ISSUE TITLE
About 617 examples

### ISSUE THREAD

**Issue by cderv** [pat-alt/quarto-example#1]
Thanks for sharing the example ! 

It is really strange as I can't reproduce on my side: running `quarto render mwe.qmd` in `617/` folder does not create an issue for me. 

Just wanted to share as maybe some updates in TeX Live are helping ? 

````
❯ tlmgr --version
tlmgr revision 62273 (2022-02-28 09:52:17 +0100)
tlmgr using installation: C:/Users/chris/AppData/Roaming/TinyTeX
TeX Live (https://tug.org/texlive) version 2022
```` 

But anyway, feel free to ignore as the issue is known with package conflict. I just can't explain why I don't have it 🤷‍♂️

**Comment by pat-alt** [comment]
Really strange 😆  I actually updated everything this morning:

```zsh
> tlmgr --version
tlmgr revision 62273 (2022-02-28 09:52:17 +0100)
tlmgr using installation: /usr/local/texlive/2022
TeX Live (https://tug.org/texlive) version 2022
```

Perhaps it's an OS issue?

```zsh
> system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 12.3.1 (21E258)
      Kernel Version: Darwin 21.4.0
...
```

Thanks anyway!

**Comment by cderv** [comment]
yeah... anyway, I'll remember if I encounter this another time 🤔
